### ISSUE TITLE
Configuration data in the "this" scope.

### ISSUE THREAD

**Issue by cfchris** [simonfree/cfAWSWrapper#1]
Simon,

Did you mean for the configuration properties (e.g SecretKey, etc) to be accessible from outside the objects? I just dumped one to make sure it was inited correctly and was a little surprised to see all of that. They are set in the "this" scope.

Unless there was a need to get/set them from outside of the object, I would prefer they be in the "variables" scope of the instances.

What do you think?

**Comment by cfchris** [comment]
If you wanted me to fork and submit an update, I'd be game.

**Comment by simonfree** [comment]
No idea what I was thinking :-) Just pushed the update.

**Comment by cfchris** [comment]
Will test change and report back. Thanks for the quick response.

**Comment by cfchris** [comment]
Worked perfect. Thank you very much.

**Comment by simonfree** [comment]
No problem. Let me know if you have any other issues.
