### ISSUE TITLE
Missing amazonSTS.cfc

### ISSUE THREAD

**Issue by mvanleest** [simonfree/cfAWSWrapper#2]
First of all, great work on the project!

I'm trying to to get bS3 buckets to work with Federated Users and you need to use the STS service for that to get the tokens.

http://docs.amazonwebservices.com/STS/latest/APIReference/Welcome.html

Are you including this in your project?

**Comment by simonfree** [comment]
I just added the STS service to the project.  Do an update and you should
see it.

On Fri, Jul 27, 2012 at 5:59 AM, mvanleest <
reply@reply.github.com

> wrote:
> 
> First of all, great work on the project!
> 
> I'm trying to to get bS3 buckets to work with Federated Users and you need
> to use the STS service for that to get the tokens.
> 
> http://docs.amazonwebservices.com/STS/latest/APIReference/Welcome.html
> 
> Are you including this in your project?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/simonfree/cfAWSWrapper/issues/2

## 

Simon Free
Adobe Community Professional
Adobe Certified Instructor

Email:simon@simonfree.com
AIM: americanshakes
URL:http://www.simonfree.com

"A train station is where the train stops. A bus station is where the bus
stops. On my desk, I have a work station..."

**Comment by mvanleest** [comment]
I'll check back in a little bit to get the STS.cfc as it is probably not processed yet. Thanks for the VERY quick reply!
